### ISSUE TITLE
provide better diagnostics when rendering fails. 

### ISSUE THREAD

**Issue by markstos** [e-conomic/phantom-render-stream#15]
Right now, rendering is failing for me in a particular environment, and this is the diagnostic I'm getting back:

    Error: Render failed
    at ReadStream.<anonymous> (/mnt/data/2/node_modules/vtmo-backend/node_modules/phantom-render-stream/index.js:34:53)
    at ReadStream.g (events.js:180:16)
    at ReadStream.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:407:10)
    at emitReadable (_stream_readable.js:403:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at ReadStream.Readable.push (_stream_readable.js:127:10)
    at onread (fs.js:1563:12)
    at Object.wrapper [as oncomplete] (fs.js:454:17)

Simply seeing "Rendered failed" is not enough to understand and address the issue. It would be great if more context could be provided in this case to help troubleshoot the issue. I need to get this to work myself, so I will be looking into this further.

**Comment by hulvei3** [comment]
see #95
